version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  inventoryservice:
    image: ${DOCKER_REGISTRY}inventoryservice
    build:
      context: .
      dockerfile: InventoryService/Dockerfile

  accountingservice:
    image: ${DOCKER_REGISTRY}accountingservice
    build:
      context: .
      dockerfile: AccountingService/Dockerfile

  shippingservice:
    image: ${DOCKER_REGISTRY}shippingservice
    build:
      context: .
      dockerfile: ShippingService/Dockerfile