version: '3.4'

services:
  inventoryservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  accountingservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  shippingservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"